// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DelhiTask.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DelhiTask
{
    public partial interface IdelhitaskContextProcedures
    {
        Task<List<SearchProductsResult>> SearchProductsAsync(string ProductName, string Size, decimal? Price, DateTime? MfgDate, string Category, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
