// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DelhiTask.Entities
{
    public partial class Product
    {
        [Key]
        [Column("ProductID")]
        public int ProductId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ProductName { get; set; }
        [StringLength(3)]
        [Unicode(false)]
        public string Size { get; set; }
        [Column("price", TypeName = "decimal(18, 0)")]
        public decimal? Price { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? MfgDate { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Category { get; set; }
    }
}